version: '3.8'

services:
  flycast-webrcade:
    build: .
    container_name: flycast-webrcade
    ports:
      - "3333:3000"
    volumes:
      - rom-storage:/app/server/roms
    restart: unless-stopped

volumes:
  rom-storage:
    driver: local
    driver_opts:
      type: cifs
      device: "//10.80.1.50/Public/Games/Dreamcast/DreamcastCHD2020_0-O"
      o: "addr=10.80.1.50,guest,sec=none,vers=3.0,file_mode=0777,dir_mode=0777"
