version: '3.8'

services:
  flycast-webrcade:
    build: .
    container_name: flycast-webrcade
    ports:
      - "3333:3000"
    volumes:
      - //MYCLOUD-0N3X91/Public/Games/Dreamcast/DreamcastCHD2020_0-O:/app/server/roms
    restart: unless-stopped
